In [5]:
import torch

In [3]:
input = torch.arange(4*4).view(1, 1, 4, 4).float()
print(input)

tensor([[[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.]]]])


In [6]:
# 创建用于上采样输入的网格
"""
步骤：
1. 创建一个网格来上采样输入张量。
2. 生成一个包含 8 个点的 1D 张量 `d`，这些点在 -1 和 1 之间线性间隔。
3. 从 `d` 创建一个网格以形成 2D 网格。
4. 堆叠网格以形成 3D 网格并添加批次维度。
5. 使用 `torch.nn.functional.grid_sample` 根据创建的网格对输入张量进行采样。
6. 打印输出张量。
变量：
- d: 包含 8 个点的 1D 张量，这些点在 -1 和 1 之间线性间隔。
- meshx, meshy: 表示网格坐标的 2D 张量。
- grid: 表示采样网格的 3D 张量，并添加了批次维度。
- output: 由网格采样操作生成的张量。
"""
d = torch.linspace(-1, 1, 8)
d


tensor([-1.0000, -0.7143, -0.4286, -0.1429,  0.1429,  0.4286,  0.7143,  1.0000])

In [9]:
"""
torch.meshgrid 是 PyTorch 中用于生成网格坐标的函数。它接受多个张量作为输入，并返回一个包含网格坐标的张量元组。让我们详细解释一下这个函数及其实现。

mesh 网格
meshgrid 用于三维曲面的分格线座标
"""
meshx, meshy = torch.meshgrid((d, d))
meshx.shape, meshx, meshy.shape, meshy


(torch.Size([8, 8]),
 tensor([[-1.0000, -1.0000, -1.0000, -1.0000, -1.0000, -1.0000, -1.0000, -1.0000],
         [-0.7143, -0.7143, -0.7143, -0.7143, -0.7143, -0.7143, -0.7143, -0.7143],
         [-0.4286, -0.4286, -0.4286, -0.4286, -0.4286, -0.4286, -0.4286, -0.4286],
         [-0.1429, -0.1429, -0.1429, -0.1429, -0.1429, -0.1429, -0.1429, -0.1429],
         [ 0.1429,  0.1429,  0.1429,  0.1429,  0.1429,  0.1429,  0.1429,  0.1429],
         [ 0.4286,  0.4286,  0.4286,  0.4286,  0.4286,  0.4286,  0.4286,  0.4286],
         [ 0.7143,  0.7143,  0.7143,  0.7143,  0.7143,  0.7143,  0.7143,  0.7143],
         [ 1.0000,  1.0000,  1.0000,  1.0000,  1.0000,  1.0000,  1.0000,  1.0000]]),
 torch.Size([8, 8]),
 tensor([[-1.0000, -0.7143, -0.4286, -0.1429,  0.1429,  0.4286,  0.7143,  1.0000],
         [-1.0000, -0.7143, -0.4286, -0.1429,  0.1429,  0.4286,  0.7143,  1.0000],
         [-1.0000, -0.7143, -0.4286, -0.1429,  0.1429,  0.4286,  0.7143,  1.0000],
         [-1.0000, -0.7143, -0.4286, -0.142

In [10]:
grid = torch.stack((meshy, meshx), 2)
grid.shape, grid

(torch.Size([8, 8, 2]),
 tensor([[[-1.0000, -1.0000],
          [-0.7143, -1.0000],
          [-0.4286, -1.0000],
          [-0.1429, -1.0000],
          [ 0.1429, -1.0000],
          [ 0.4286, -1.0000],
          [ 0.7143, -1.0000],
          [ 1.0000, -1.0000]],
 
         [[-1.0000, -0.7143],
          [-0.7143, -0.7143],
          [-0.4286, -0.7143],
          [-0.1429, -0.7143],
          [ 0.1429, -0.7143],
          [ 0.4286, -0.7143],
          [ 0.7143, -0.7143],
          [ 1.0000, -0.7143]],
 
         [[-1.0000, -0.4286],
          [-0.7143, -0.4286],
          [-0.4286, -0.4286],
          [-0.1429, -0.4286],
          [ 0.1429, -0.4286],
          [ 0.4286, -0.4286],
          [ 0.7143, -0.4286],
          [ 1.0000, -0.4286]],
 
         [[-1.0000, -0.1429],
          [-0.7143, -0.1429],
          [-0.4286, -0.1429],
          [-0.1429, -0.1429],
          [ 0.1429, -0.1429],
          [ 0.4286, -0.1429],
          [ 0.7143, -0.1429],
          [ 1.0000, -0.1429]],
 
    

In [11]:
grid = grid.unsqueeze(0) # add batch dim
grid.shape, grid

(torch.Size([1, 8, 8, 2]),
 tensor([[[[-1.0000, -1.0000],
           [-0.7143, -1.0000],
           [-0.4286, -1.0000],
           [-0.1429, -1.0000],
           [ 0.1429, -1.0000],
           [ 0.4286, -1.0000],
           [ 0.7143, -1.0000],
           [ 1.0000, -1.0000]],
 
          [[-1.0000, -0.7143],
           [-0.7143, -0.7143],
           [-0.4286, -0.7143],
           [-0.1429, -0.7143],
           [ 0.1429, -0.7143],
           [ 0.4286, -0.7143],
           [ 0.7143, -0.7143],
           [ 1.0000, -0.7143]],
 
          [[-1.0000, -0.4286],
           [-0.7143, -0.4286],
           [-0.4286, -0.4286],
           [-0.1429, -0.4286],
           [ 0.1429, -0.4286],
           [ 0.4286, -0.4286],
           [ 0.7143, -0.4286],
           [ 1.0000, -0.4286]],
 
          [[-1.0000, -0.1429],
           [-0.7143, -0.1429],
           [-0.4286, -0.1429],
           [-0.1429, -0.1429],
           [ 0.1429, -0.1429],
           [ 0.4286, -0.1429],
           [ 0.7143, -0.1429],
   

In [13]:
output = torch.nn.functional.grid_sample(input, grid)
input.shape, input, output.shape, output

# 完全不懂


(torch.Size([1, 1, 4, 4]),
 tensor([[[[ 0.,  1.,  2.,  3.],
           [ 4.,  5.,  6.,  7.],
           [ 8.,  9., 10., 11.],
           [12., 13., 14., 15.]]]]),
 torch.Size([1, 1, 8, 8]),
 tensor([[[[ 0.0000,  0.0357,  0.3214,  0.6071,  0.8929,  1.1786,  1.4643,
             0.7500],
           [ 0.1429,  0.3571,  0.9286,  1.5000,  2.0714,  2.6429,  3.2143,
             1.6429],
           [ 1.2857,  2.6429,  3.2143,  3.7857,  4.3571,  4.9286,  5.5000,
             2.7857],
           [ 2.4286,  4.9286,  5.5000,  6.0714,  6.6429,  7.2143,  7.7857,
             3.9286],
           [ 3.5714,  7.2143,  7.7857,  8.3571,  8.9286,  9.5000, 10.0714,
             5.0714],
           [ 4.7143,  9.5000, 10.0714, 10.6429, 11.2143, 11.7857, 12.3571,
             6.2143],
           [ 5.8571, 11.7857, 12.3571, 12.9286, 13.5000, 14.0714, 14.6429,
             7.3571],
           [ 3.0000,  6.0357,  6.3214,  6.6071,  6.8929,  7.1786,  7.4643,
             3.7500]]]]))